/* Predictive Analytics — job enrichment (EN / IT). See content-intel.js for keys. */
window.CONTENT = window.CONTENT || {};
Object.assign(window.CONTENT, {
  "learn::job::learn-packet": {
    l: ["The campaign's data, collected as it runs.", "I dati della campagna, raccolti mentre gira."],
    b: ["The agent tracks which learning slots have data and chases only the gaps.", "L'agente controlla quali slot di apprendimento hanno dati e sollecita solo le lacune."],
    a: ["Collection agent", "Agente raccolta"],
    ad: "AEP · Customer Journey Analytics",
    op: "Data pipeline + BI",
    tr: ["Learn packet arrives from Activation.", "Il learn packet arriva da Activation."],
    do: ["Checks coverage per slot, requests missing sources.", "Verifica la copertura per slot, richiede le fonti mancanti."],
    out: ["Packet status.", "Stato del packet."],
    gate: ["Analyst on missing slots.", "L'analista sugli slot mancanti."],
    it: { r: "Chiedere il file al media alla sesta settimana.", lad: ["Un'email di sollecito.", "Le lacune sono elencate. Una persona sollecita solo quelle.", "Il packet arriva mentre la campagna gira."], h: "L'analista sugli slot mancanti.", n: "Se il packet è vuoto, si ferma. Non modella un ricordo." }
  },
  "learn::job::join-clean": {
    l: ["One trusted dataset.", "Un unico dataset affidabile."],
    b: ["The data engineering agent joins media, web, CRM and sales data at an agreed grain and flags quality issues.", "L'agente di data engineering unisce dati media, web, CRM e vendite a un livello di dettaglio concordato e segnala i problemi di qualità."],
    a: ["Data engineering agent", "Agente data engineering"],
    ad: "AEP Data Engineering Agent · Customer Journey Analytics",
    op: "Data platform + pipeline tooling",
    tr: ["New data lands.", "Arrivano nuovi dati."],
    do: ["Maps schemas, joins, deduplicates, validates.", "Mappa gli schemi, unisce, deduplica, valida."],
    out: ["Trusted set.", "Dataset affidabile."],
    gate: ["Analytics engineer on new sources.", "L'analytics engineer sulle nuove fonti."],
    it: { r: "Un export arrivato tardi che non corrisponde più ai dati attuali.", lad: ["Il CERCA.VERT come stile di vita.", "I join girano. L'analista firma il livello di dettaglio.", "Le pipeline note arrivano ogni notte."], h: "L'analytics engineer sulle nuove fonti.", n: "Location analytics e journey analytics attingono entrambi da questo dataset." }
  },
  "learn::job::kpi-dictionary": {
    l: ["One definition for every number.", "Una sola definizione per ogni numero."],
    b: ["The agent drafts and checks KPI definitions across teams. The analytics lead locks the dictionary.", "L'agente propone e verifica le definizioni dei KPI tra i team. L'analytics lead blocca il dizionario."],
    a: ["Metrics agent", "Agente metriche"],
    ad: "Customer Journey Analytics (calculated metrics) · Data Insights Agent",
    op: "Semantic layer / BI",
    tr: ["New KPI or a conflicting definition.", "Un nuovo KPI o una definizione in conflitto."],
    do: ["Finds duplicates and conflicts; drafts definitions.", "Trova duplicati e conflitti; propone le definizioni."],
    out: ["Draft dictionary changes.", "Modifiche al dizionario in bozza."],
    gate: ["Analytics lead plus the CMO's designate lock.", "L'analytics lead e il delegato del CMO bloccano."],
    it: { r: "Una slide con quattordici semafori verdi.", lad: ["Ogni team si inventa la sua north star.", "Un dizionario in bozza. Il lead blocca.", "Mai il blocco."], h: "L'analytics lead e il delegato del CMO.", n: "Gli slot del ciclo successivo puntano a questi nomi." }
  },
  "learn::job::incrementality": {
    l: ["What the campaign really caused.", "Cosa ha causato davvero la campagna."],
    b: ["The agent designs holdout and geo tests from the last model and reads results. The measurement lead runs and signs them.", "L'agente progetta test holdout e geografici dall'ultimo modello e ne legge i risultati. Il measurement lead li esegue e li firma."],
    a: ["Experimentation agent", "Agente sperimentazione"],
    ad: "AEP Experimentation Agent · Mix Modeler",
    op: "Experimentation platform",
    tr: ["Planned test window opens.", "Si apre la finestra di test pianificata."],
    do: ["Designs test cells, sizes them, reads lift.", "Progetta le celle di test, le dimensiona, legge l'incremento."],
    out: ["Incrementality results.", "Risultati di incrementalità."],
    gate: ["Measurement lead signs.", "Il measurement lead firma."],
    it: { r: "Il ROAS della piattaforma scambiato per causalità.", lad: ["Un test che nessuno ha progettato.", "Disegno dall'ultimo modello. Una persona esegue l'holdout.", "Holdout continui dopo un pattern collaudato."], h: "Measurement lead.", n: "I risultati aggiornano il modello di mix." }
  },
  "learn::job::mix-models": {
    l: ["The contribution of every channel, refreshed.", "Il contributo di ogni canale, aggiornato."],
    b: ["Mix models re-estimate on a schedule with incrementality as calibration. An analyst signs every refresh.", "I modelli di mix si ricalcolano a intervalli regolari, calibrati con l'incrementalità. Un analista firma ogni aggiornamento."],
    a: ["Mix modelling agent", "Agente mix modelling"],
    ad: "Adobe Mix Modeler",
    op: "MMM platform",
    tr: ["Scheduled refresh or new test results.", "Aggiornamento programmato o nuovi risultati di test."],
    do: ["Re-estimates, compares to the last model, explains changes.", "Ricalcola, confronta con l'ultimo modello, spiega le differenze."],
    out: ["Mix model and response curves.", "Modello di mix e curve di risposta."],
    gate: ["Analyst signs each refresh.", "L'analista firma ogni aggiornamento."],
    it: { r: "Un media mix basato sulla share of voice dell'anno scorso.", lad: ["Un fornitore black box una volta l'anno.", "Il modello si aggiorna. L'analista firma.", "Le specifiche note si ricalcolano a calendario."], h: "L'analista firma ogni aggiornamento.", n: "Il solo media mix (paid) non basta. Il marketing mix include brand, prezzo, distribuzione." }
  },
  "learn::job::scenarios": {
    l: ["What happens if we spend differently.", "Cosa succede se spendiamo diversamente."],
    b: ["The agent simulates budget scenarios on the response curves and ranks them. The media lead picks.", "L'agente simula scenari di budget sulle curve di risposta e li ordina. Il media lead sceglie."],
    a: ["Scenario agent", "Agente scenari"],
    ad: "Adobe Mix Modeler (planner)",
    op: "MMM planner",
    tr: ["Planning cycle or budget change.", "Ciclo di pianificazione o cambio di budget."],
    do: ["Runs scenarios with constraints and confidence ranges.", "Simula scenari con vincoli e intervalli di confidenza."],
    out: ["Ranked scenarios.", "Scenari ordinati."],
    gate: ["Media lead picks; analytics prepares.", "Il media lead sceglie; analytics prepara."],
    it: { r: "Un workshop di pianificazione senza curve.", lad: ["Pancia più anno scorso.", "Scenari ordinati. Una persona sceglie.", "Le bozze si aggiornano. La scelta resta umana."], h: "Il media lead sceglie. Analytics prepara.", n: "È il file che Spend in Activation sta aspettando." }
  },
  "learn::job::brand-tracking": {
    l: ["Brand health between survey waves.", "La salute del brand tra un'ondata di survey e l'altra."],
    b: ["Survey waves stay the anchor. The agent fills the gaps with digital signals so brand is visible every week.", "Le ondate di survey restano il riferimento. L'agente colma i vuoti con segnali digitali, così il brand è visibile ogni settimana."],
    a: ["Brand tracking agent", "Agente brand tracking"],
    ad: "Customer Journey Analytics · LLM Optimizer (AI visibility)",
    op: "Brand tracker + social / search data",
    tr: ["Weekly between waves.", "Ogni settimana tra le ondate."],
    do: ["Blends survey, search, social and AI-visibility signals.", "Combina segnali da survey, ricerca, social e visibilità AI."],
    out: ["Brand tracking view.", "Vista di brand tracking."],
    gate: ["Insights lead edits the read-out.", "L'insights lead modifica la lettura."],
    it: { r: "Sei mesi senza visibilità.", lad: ["Solo una survey.", "Ondate più dati digitali. Insights modifica.", "I dati digitali girano tra le ondate."], h: "Insights lead.", n: "Il digitale non sostituisce l'ondata. Serve a vedere tra un'ondata e l'altra." }
  },
  "learn::job::equity-model": {
    l: ["What actually drives the brand.", "Cosa fa crescere davvero il brand."],
    b: ["The agent ranks brand drivers and their link to sales on a schedule. Brand signs the north star.", "L'agente ordina i driver del brand e il loro legame con le vendite a intervalli regolari. Il brand firma la north star."],
    a: ["Equity agent", "Agente equity"],
    ad: "Adobe Mix Modeler · Customer Journey Analytics",
    op: "Brand equity model + BI",
    tr: ["Scheduled refresh.", "Aggiornamento programmato."],
    do: ["Re-estimates drivers, explains shifts.", "Ricalcola i driver, spiega gli spostamenti."],
    out: ["Equity model.", "Modello di equity."],
    gate: ["Brand lead signs the north star.", "Il brand lead firma la north star."],
    it: { r: "La notorietà come unico KPI di brand.", lad: ["Un framework su un poster.", "Driver ordinati. Il brand firma la north star.", "Aggiornamento a calendario. Il blocco resta umano."], h: "Il brand lead firma la north star.", n: "I modelli usano i vincoli di equity insieme agli altri input di pianificazione." }
  },
  "learn::job::content-scores": {
    l: ["Which content worked, and why.", "Quali contenuti hanno funzionato, e perché."],
    b: ["The agent scores every asset by attributes (format, message, visual) against outcomes, so the next brief knows what to make more of.", "L'agente valuta ogni asset per attributi (formato, messaggio, visual) rispetto ai risultati, così il prossimo brief sa cosa produrre di più."],
    a: ["Content analytics agent", "Agente content analytics"],
    ad: "GenStudio content insights · Customer Journey Analytics",
    op: "Creative analytics",
    tr: ["Asset has enough delivery.", "L'asset ha abbastanza erogazione."],
    do: ["Tags attributes, links them to performance.", "Tagga gli attributi, li collega alle performance."],
    out: ["Content scores.", "Punteggi dei contenuti."],
    gate: ["Creative and brand decide what to retire.", "Creativi e brand decidono cosa ritirare."],
    it: { r: "Le visualizzazioni come misura di qualità.", lad: ["Un premio creativo.", "I punteggi arrivano. I creativi leggono cosa significano.", "I pack noti si valutano da soli."], h: "Creativi e brand su cosa ritirare.", n: "Amplify-winners in Activation è spesa. Questo è apprendimento." }
  },
  "learn::job::pathing": {
    l: ["How people really move.", "Come si muovono davvero le persone."],
    b: ["The agent maps the most common and most valuable paths across owned, paid and physical touchpoints.", "L'agente mappa i percorsi più frequenti e più di valore tra touchpoint owned, paid e fisici."],
    a: ["Path analysis agent", "Agente analisi percorsi"],
    ad: "Customer Journey Analytics · Data Insights Agent",
    op: "Journey analytics",
    tr: ["Trusted set refreshes.", "Il dataset affidabile si aggiorna."],
    do: ["Builds path flows, segments them by value.", "Costruisce i flussi di percorso, li segmenta per valore."],
    out: ["Path set.", "Set di percorsi."],
    gate: ["Journey lead names the valuable path.", "Il journey lead indica il percorso di valore."],
    it: { r: "Una storia last-click.", lad: ["Un'ipotesi.", "Percorsi elencati. Una persona indica quello che conta.", "I livelli di dettaglio noti si aggiornano."], h: "Il journey lead indica il percorso di valore.", n: "Alimenta i testi journey del ciclo successivo entro il territorio approvato." }
  },
  "learn::job::friction": {
    l: ["Where people drop out.", "Dove le persone abbandonano."],
    b: ["The agent ranks friction points by lost value and suggests a likely cause. The experience lead picks which to fix.", "L'agente ordina i punti di attrito per valore perso e suggerisce una causa probabile. L'experience lead sceglie quali correggere."],
    a: ["Friction agent", "Agente attriti"],
    ad: "Customer Journey Analytics · Sites Optimizer",
    op: "Journey analytics + session analysis",
    tr: ["Drop-off above normal.", "Abbandono sopra la norma."],
    do: ["Detects anomalies, estimates impact, links evidence.", "Rileva anomalie, stima l'impatto, collega le evidenze."],
    out: ["Friction log.", "Log degli attriti."],
    gate: ["Experience or journey lead picks the fight.", "L'experience o journey lead sceglie su cosa intervenire."],
    it: { r: "Un bounce rate senza responsabile.", lad: ["Un reclamo.", "Attriti ordinati. Una persona sceglie su cosa intervenire.", "Le perdite note generano un alert."], h: "Experience o journey lead.", n: "Un'idea nuova va a Routes. Uno step rotto è un facelift o un intervento di ottimizzazione." }
  },
  "learn::job::increment-paths": {
    l: ["Which steps really add value.", "Quali step aggiungono davvero valore."],
    b: ["The agent designs tests on journey steps to separate correlation from contribution. The measurement lead reads the result.", "L'agente progetta test sugli step del journey per distinguere correlazione e contributo. Il measurement lead legge il risultato."],
    a: ["Path testing agent", "Agente test sui percorsi"],
    ad: "AEP Experimentation Agent · Journey Optimizer",
    op: "Experimentation + orchestration",
    tr: ["Valuable path is named.", "Il percorso di valore è stato indicato."],
    do: ["Sets up holdouts on steps, reads lift.", "Imposta holdout sugli step, legge l'incremento."],
    out: ["Path increment.", "Incremento per percorso."],
    gate: ["Measurement lead reads and signs.", "Il measurement lead legge e firma."],
    it: { r: "“Aprire la mail ha causato la vendita.”", lad: ["La correlazione come strategia.", "Un test sul percorso. Una persona legge.", "Dopo che il disegno è collaudato."], h: "Measurement lead.", n: "Calibra Orchestrate. Non riscrive la hero." }
  },
  "learn::job::segments": {
    l: ["Segments based on behaviour.", "Segmenti basati sui comportamenti."],
    b: ["The audience agent proposes clusters from the trusted set and detects shifts. Insights names them.", "L'audience agent propone cluster dal dataset affidabile e rileva i cambiamenti. Insights dà loro un nome."],
    a: ["Audience agent", "Agente audience"],
    ad: "AEP Audience Agent · Real-Time CDP",
    op: "CDP + clustering",
    tr: ["Trusted set refreshes.", "Il dataset affidabile si aggiorna."],
    do: ["Clusters, sizes, compares to existing audiences.", "Crea cluster, li dimensiona, li confronta con i pubblici esistenti."],
    out: ["Segments.", "Segmenti."],
    gate: ["Insights names the cut.", "Insights dà un nome al taglio."],
    it: { r: "25–45 anni, urbani.", lad: ["Un workshop sulle persona.", "Cluster proposti. Insights dà un nome.", "I tagli noti si aggiornano."], h: "Insights dà un nome al taglio.", n: "La profondità delle persona resta in Strategy. Questa è evidenza." }
  },
  "learn::job::location-analytics": {
    l: ["Where it worked, place by place.", "Dove ha funzionato, luogo per luogo."],
    b: ["The agent ranks markets, regions and stores by response so the next market matrix is based on evidence.", "L'agente ordina mercati, regioni e punti vendita per risposta, così la prossima matrice di mercato si basa su evidenze."],
    a: ["Location agent", "Agente location"],
    ad: "Customer Journey Analytics · Data Insights Agent",
    op: "Geo analytics + BI",
    tr: ["Trusted set refreshes.", "Il dataset affidabile si aggiorna."],
    do: ["Compares places against baseline and spend.", "Confronta i luoghi con la baseline e la spesa."],
    out: ["Location insight.", "Insight per location."],
    gate: ["Local / commercial lead reads the so-what.", "Il local / commercial lead legge le implicazioni."],
    it: { r: "Tutti i mercati, allo stesso modo.", lad: ["Una mappa di calore in una presentazione.", "Luoghi ordinati. Il lead locale legge.", "I territori noti si aggiornano."], h: "Il local / commercial lead sulle implicazioni.", n: "Alimenta la matrice di mercato del ciclo successivo. Non prenota media." }
  },
  "learn::job::sales-intelligence": {
    l: ["Marketing and sales reading the same numbers.", "Marketing e vendite leggono gli stessi numeri."],
    b: ["The agent connects campaign exposure to commercial results and drafts the read-out. The commercial lead edits.", "L'agente collega l'esposizione alla campagna ai risultati commerciali e prepara la lettura. Il commercial lead modifica."],
    a: ["Sales insight agent", "Agente sales insight"],
    ad: "Customer Journey Analytics · Adobe Marketing Agent (M365 Copilot)",
    op: "BI + CRM / ERP data",
    tr: ["Sales data lands.", "Arrivano i dati di vendita."],
    do: ["Joins commercial data, drafts insight with sources.", "Unisce i dati commerciali, prepara l'insight con le fonti."],
    out: ["Commercial insight.", "Insight commerciale."],
    gate: ["Commercial / RGM lead edits.", "Il commercial / RGM lead modifica."],
    it: { r: "Un report di marketing scollegato dal team commerciale.", lad: ["Una BI vendite separata.", "Insight in bozza. Il commerciale modifica.", "Le viste note si aggiornano."], h: "Commercial / RGM lead.", n: "Un unico dataset affidabile condiviso dal team." }
  },
  "learn::job::trend-radar": {
    l: ["The trends worth acting on.", "I trend su cui vale la pena agire."],
    b: ["The agent scans continuously and clusters emerging themes. Strategy decides which ones matter.", "L'agente analizza in continuo e raggruppa i temi emergenti. La strategia decide quali contano."],
    a: ["Trend agent", "Agente trend"],
    ad: "LLM Optimizer",
    op: "Trend and search intelligence",
    tr: ["Continuous.", "Continuo."],
    do: ["Detects rising themes, dates and sources them.", "Rileva i temi in crescita, li data e ne indica le fonti."],
    out: ["Trend map.", "Mappa dei trend."],
    gate: ["Strategist / innovation lead clusters.", "Strategist / innovation lead raggruppa."],
    it: { r: "La slide dei trend di un keynote.", lad: ["Un workshop annuale.", "Il radar propone. Una persona raggruppa.", "L'analisi gira. I cluster restano umani."], h: "Strategist / innovation lead.", n: "Alimenta la pianificazione strategica e il brief successivo come contesto di mercato." }
  },
  "learn::job::market-listening": {
    l: ["What people say, in every market.", "Cosa dicono le persone, in ogni mercato."],
    b: ["The agent listens across markets and languages, ranks topics and dates every note.", "L'agente ascolta mercati e lingue diversi, ordina i temi e data ogni nota."],
    a: ["Listening agent", "Agente ascolto"],
    ad: "Social listening via MCP · LLM Optimizer",
    op: "Social listening",
    tr: ["Continuous.", "Continuo."],
    do: ["Collects, translates, ranks and cites.", "Raccoglie, traduce, ordina e cita le fonti."],
    out: ["Listening log.", "Log di ascolto."],
    gate: ["Insights on citation.", "Insights sulle citazioni."],
    it: { r: "Una clip solo dal mercato principale.", lad: ["Premi e aneddoti.", "Ascolto ordinato. Una persona cita.", "Le fonti note girano."], h: "Insights sulle citazioni.", n: "Ogni nota deve avere una data." }
  },
  "learn::job::competitive-watch": {
    l: ["What competitors did during our flight.", "Cosa hanno fatto i competitor durante la nostra campagna."],
    b: ["The agent compiles competitor moves after the flight, including how AI assistants now describe them. The strategist marks the gap.", "L'agente raccoglie le mosse dei competitor dopo la campagna, incluso come gli assistenti AI li descrivono ora. Lo strategist segna lo spazio libero."],
    a: ["Competitive agent", "Agente competitivo"],
    ad: "LLM Optimizer",
    op: "Competitive intelligence",
    tr: ["End of flight; then weekly.", "Fine campagna; poi settimanale."],
    do: ["Compiles moves, share of voice and AI visibility.", "Raccoglie mosse, share of voice e visibilità AI."],
    out: ["Competitive note.", "Nota competitiva."],
    gate: ["Strategist owns the gap.", "Lo strategist è responsabile della lettura."],
    it: { r: "Qualcuno ha visto un annuncio venendo in ufficio.", lad: ["Uno screenshot.", "Analisi compilata. Lo strategist segna lo spazio libero.", "I set noti si aggiornano."], h: "Lo strategist è responsabile della lettura.", n: "Stessa famiglia di oggetti di Strategy. Questa è dopo la campagna." }
  },
  "learn::job::forecast": {
    l: ["A range for the next cycle, not a guess.", "Un intervallo per il prossimo ciclo, non una stima a occhio."],
    b: ["The agent forecasts outcomes with confidence ranges from the mix and equity models. Finance and analytics pick the plan.", "L'agente prevede i risultati con intervalli di confidenza dai modelli di mix ed equity. Finance e analytics scelgono il piano."],
    a: ["Forecast agent", "Agente forecast"],
    ad: "Adobe Mix Modeler · Customer Journey Analytics",
    op: "Forecasting + BI",
    tr: ["Models are signed.", "I modelli sono firmati."],
    do: ["Projects ranges, compares to targets, explains drivers.", "Proietta intervalli, li confronta con i target, spiega i driver."],
    out: ["Forecast.", "Forecast."],
    gate: ["Analytics plus finance pick the plan.", "Analytics e finance scelgono il piano."],
    it: { r: "Un target della finance senza curva.", lad: ["Un numero tondo.", "Un intervallo. Una persona sceglie il piano.", "L'intervallo si aggiorna."], h: "Analytics e finance.", n: "La precisione può migliorare a ogni ciclo. È la promessa di questa fase." },
    n: "Accuracy compounds every cycle. That is the promise of this phase."
  },
  "learn::job::next-cycle-brief": {
    l: ["The next brief starts from evidence.", "Il prossimo brief parte dalle evidenze."],
    b: ["The agent fills the learning slots with route, claim, segment and market evidence from the completed cycle, and drafts the next brief.", "L'agente compila gli slot di apprendimento con evidenze su route, claim, segmenti e mercati del ciclo concluso, e prepara il brief successivo."],
    a: ["Brief compiler", "Compilatore del brief"],
    ad: "Brand Intelligence · Workfront",
    op: "Agent orchestration + document store",
    tr: ["Cycle closes.", "Il ciclo si chiude."],
    do: ["Answers each slot, cites evidence, drafts the brief.", "Risponde a ogni slot, cita le evidenze, prepara il brief."],
    out: ["Draft next-cycle brief in the Company Brain.", "Bozza del brief successivo nel Company Brain."],
    gate: ["Strategist plus demand owner sign.", "Strategist e demand owner firmano."],
    it: { r: "Ripartire dalla pagina bianca.", lad: ["Un kickoff senza file.", "Il compilatore propone. Lo strategist modifica.", "Il sistema compila gli slot; l'owner firma il brief."], h: "Strategist e demand owner.", n: "È l'oggetto che Demand e Brief stavano aspettando." }
  },
  "learn::job::recommendation": {
    l: ["What to keep, cut and add next time.", "Cosa tenere, tagliare e aggiungere la prossima volta."],
    b: ["One signed page: keep, cut, add, and why. Allocation in the next cycle cannot run without it.", "Una pagina firmata: cosa tenere, tagliare, aggiungere, e perché. L'allocazione del ciclo successivo non parte senza."],
    a: ["Recommendation drafter", "Agente raccomandazione"],
    ad: "Mix Modeler",
    op: "Agent orchestration + MMM",
    tr: ["Models, scores and forecast are signed.", "Modelli, punteggi e forecast sono firmati."],
    do: ["Drafts the one-page recommendation with evidence links.", "Prepara la raccomandazione di una pagina con i link alle evidenze."],
    out: ["Draft recommendation.", "Raccomandazione in bozza."],
    gate: ["Analytics lead signs; media and brand countersign.", "L'analytics lead firma; media e brand controfirmano."],
    it: { r: "Un'appendice di 60 pagine.", lad: ["Un'opinione in corridoio.", "La pagina è in bozza. Una persona firma.", "Mai la firma."], h: "Analytics lead. Media e brand controfirmano.", n: "L'owner di Learn approva la raccomandazione finale." }
  }
});
