/* Intelligent Activation — job enrichment (EN / IT). See content-intel.js for keys. */
window.CONTENT = window.CONTENT || {};
Object.assign(window.CONTENT, {
  "act::job::sizes-crops": {
    l: ["Every size and crop, from one master.", "Ogni formato e ritaglio, da un unico master."],
    b: ["The agent generates placement-ready versions from the hero and hub assets within the art direction. Humans spot-check.", "L'agente genera versioni pronte per ogni placement dagli asset hero e hub, entro l'art direction. Le persone fanno controlli a campione."],
    a: ["Resize agent", "Agente resize"],
    ad: "GenStudio for Performance Marketing · Firefly (generative expand)",
    op: "Automated resizing + gen-AI fill",
    tr: ["Master pack is signed.", "Il master pack è firmato."],
    do: ["Crops, expands and re-composes for each format.", "Ritaglia, estende e ricompone per ogni formato."],
    out: ["Crop set.", "Set di ritagli."],
    gate: ["Studio steps in only when a crop breaks the route.", "Lo studio interviene solo se un ritaglio tradisce la route."],
    it: { r: "Un designer per ogni formato.", lad: ["Ogni formato viene ridisegnato.", "Ritagli proposti. Una persona controlla volti e testi.", "I template firmati girano."], h: "Lo studio interviene solo quando un ritaglio tradisce la route.", n: "Se il ritaglio richiede un nuovo scatto, è Hero, non questo." }
  },
  "act::job::languages": {
    l: ["Every market version, in the right voice.", "Ogni versione di mercato, con la voce giusta."],
    b: ["The agent localises approved copy and claims using translation memory and brand terms. Native editors check new language pairs.", "L'agente localizza testi e claim approvati usando memorie di traduzione e terminologia di brand. Editor madrelingua controllano le nuove coppie linguistiche."],
    a: ["Localisation agent", "Agente localizzazione"],
    ad: "GenStudio for Performance Marketing · AEM translation",
    op: "Translation management + LLM",
    tr: ["Market matrix lists the language.", "La matrice di mercato prevede la lingua."],
    do: ["Translates, adapts length, checks local claims.", "Traduce, adatta la lunghezza, verifica i claim locali."],
    out: ["Language set.", "Set linguistico."],
    gate: ["Native editor on first use of a pair.", "Editor madrelingua al primo utilizzo di una coppia."],
    it: { r: "Una riscrittura freelance che diventa una seconda campagna.", lad: ["Ogni lingua è un nuovo copywriter.", "La memoria propone. Un editor madrelingua controlla.", "Le coppie note girano."], h: "Editor madrelingua al primo utilizzo di una coppia.", n: "I Do-nots valgono sempre. Una traduzione può violare un claim." }
  },
  "act::job::placement-specs": {
    l: ["Exact requirements for every placement.", "I requisiti esatti per ogni placement."],
    b: ["The agent keeps the channel specs current and checks every variant against them before delivery.", "L'agente mantiene aggiornate le specifiche dei canali e verifica ogni variante prima della consegna."],
    a: ["Spec agent", "Agente specifiche"],
    ad: "GenStudio for Performance Marketing (channel connectors)",
    op: "Ad-platform APIs + preflight",
    tr: ["Bookings list placements.", "Le prenotazioni elencano i placement."],
    do: ["Pulls specs from platforms; validates variants.", "Recupera le specifiche dalle piattaforme; valida le varianti."],
    out: ["Spec set.", "Set di specifiche."],
    gate: ["Activation ops on new placements.", "Activation ops sui nuovi placement."],
    it: { r: "Il media che rifiuta il file a campagna già prenotata.", lad: ["Qualcuno legge la scheda tecnica.", "Controlli rispetto al pack.", "I placement noti si compilano."], h: "Activation ops sui nuovi placement.", n: "La personalizzazione può scegliere da questo set. Non può inventare un nuovo master." }
  },
  "act::job::allocate": {
    l: ["Where the money goes.", "Dove vanno i soldi."],
    b: ["The agent turns Learn's recommendation into a proposed channel split with scenarios. The media lead locks the money.", "L'agente trasforma la raccomandazione di Learn in una proposta di ripartizione tra canali con scenari. Il media lead blocca il budget."],
    a: ["Budget agent", "Agente budget"],
    ad: "Adobe Mix Modeler",
    op: "MMM + planning tool",
    tr: ["Learn recommendation is signed.", "La raccomandazione di Learn è firmata."],
    do: ["Builds the split, shows trade-offs and risks.", "Costruisce la ripartizione, mostra trade-off e rischi."],
    out: ["Proposed channel mix.", "Mix di canali proposto."],
    gate: ["Media lead plus finance lock.", "Media lead e finance bloccano."],
    it: { r: "Fette uguali, o a chi ha urlato di più.", lad: ["Una presentazione di pianificazione.", "Le curve propongono. Una persona blocca.", "Mai il blocco."], h: "Media lead.", n: "Se Learn non ha una raccomandazione, si ferma e lo dice." }
  },
  "act::job::book-channels": {
    l: ["Bookings that match the plan.", "Prenotazioni coerenti con il piano."],
    b: ["The agent drafts insertion orders and platform set-ups from the locked mix. The buyer confirms.", "L'agente prepara ordini di inserzione e configurazioni sulle piattaforme dal mix bloccato. Il buyer conferma."],
    a: ["Booking agent", "Agente booking"],
    ad: "GenStudio for Performance Marketing (activation) · Workfront",
    op: "Ad-platform APIs + work management",
    tr: ["Mix is locked and master pack signed.", "Il mix è bloccato e il master pack firmato."],
    do: ["Drafts campaigns, budgets and flights per platform.", "Prepara campagne, budget e periodi per piattaforma."],
    out: ["Draft bookings.", "Prenotazioni in bozza."],
    gate: ["Buyer / trading confirms.", "Buyer / trading conferma."],
    it: { r: "Un ordine di inserzione in ritardo e un flight perso.", lad: ["I buyer mandano gli IO via email.", "L'agente prepara la prenotazione. Il buyer conferma.", "Solo linee always-on, dopo un template umano."], h: "Buyer / trading.", n: "Nessuna prenotazione senza master pack firmato e mix bloccato." }
  },
  "act::job::pacing": {
    l: ["Spend on track, every day.", "Spesa sotto controllo, ogni giorno."],
    b: ["The agent watches delivery and spend daily and flags drift early. Any budget move waits for a person.", "L'agente monitora consegna e spesa ogni giorno e segnala in anticipo gli scostamenti. Ogni spostamento di budget aspetta una persona."],
    a: ["Pacing agent", "Agente pacing"],
    ad: "Customer Journey Analytics",
    op: "Media analytics + alerts",
    tr: ["Daily during flight.", "Ogni giorno durante la campagna."],
    do: ["Compares delivery to plan, forecasts end-of-flight.", "Confronta la consegna con il piano, stima il risultato a fine campagna."],
    out: ["Pacing log and alerts.", "Log di pacing e alert."],
    gate: ["Media lead approves any move.", "Il media lead approva ogni spostamento."],
    it: { r: "Un problema di consegna scoperto dopo il lancio.", lad: ["Un foglio Excel settimanale.", "Gli scostamenti sono segnalati. Una persona decide.", "Gli alert girano. Gli spostamenti aspettano."], h: "Il media lead su ogni spostamento.", n: "Le modifiche creative in corso stanno in Orchestrate. Qui si parla solo di soldi." }
  },
  "act::job::organic-calendar": {
    l: ["The organic plan, from one content kit.", "Il piano organico, da un unico kit di contenuti."],
    b: ["The agent proposes posting slots and captions from the hub pack. The social lead locks the calendar.", "L'agente propone slot di pubblicazione e caption dal pack hub. Il social lead blocca il calendario."],
    a: ["Social planning agent", "Agente pianificazione social"],
    ad: "GenStudio for Performance Marketing · Workfront",
    op: "Social management platform + LLM",
    tr: ["Hub pack is approved.", "Il pack hub è approvato."],
    do: ["Drafts the calendar, captions and local adaptations.", "Prepara calendario, caption e adattamenti locali."],
    out: ["Social calendar draft.", "Bozza di calendario social."],
    gate: ["Social lead locks; locals adapt within the pack.", "Il social lead blocca; i team locali adattano entro il pack."],
    it: { r: "Un post dell'ultimo minuto che viola il claim.", lad: ["Qualcuno pubblica dal telefono.", "Il kit propone gli slot. Il social lead blocca.", "Solo slot a basso rischio, dopo un pattern collaudato."], h: "Il social lead è responsabile del calendario; i team locali lo adattano entro il pack approvato.", n: "Il paid social usa il calendario e il pack approvati." }
  },
  "act::job::paid-social": {
    l: ["Paid social from the approved kit.", "Paid social dal kit approvato."],
    b: ["The agent builds ad sets from approved variants and runs them on known placements. The buyer sets bids and budgets.", "L'agente costruisce gli ad set dalle varianti approvate e li attiva sui placement noti. Il buyer imposta offerte e budget."],
    a: ["Paid social agent", "Agente paid social"],
    ad: "GenStudio for Performance Marketing (Meta, TikTok, LinkedIn…)",
    op: "Ad-platform APIs",
    tr: ["Calendar and bookings exist.", "Esistono calendario e prenotazioni."],
    do: ["Assembles ads, audiences and tests from the pack.", "Assembla annunci, pubblici e test dal pack."],
    out: ["Live paid social set.", "Set paid social attivo."],
    gate: ["Buyer sets bids; brand control checks live.", "Il buyer imposta le offerte; brand control verifica online."],
    it: { r: "Contenuti paid social senza approvazione del brand.", lad: ["Ogni annuncio è un nuovo concept.", "Le declinazioni riempiono il set. Il buyer imposta l'offerta.", "I placement noti girano dal pack."], h: "Social / performance buyer.", n: "Se l'annuncio richiede un'idea nuova, torna a Routes." }
  },
  "act::job::amplify-winners": {
    l: ["Put money behind what already works.", "Investire su ciò che funziona già."],
    b: ["The agent ranks organic winners and boosts those above the agreed bar, within the approved budget.", "L'agente ordina i contenuti organici migliori e spinge quelli sopra la soglia concordata, entro il budget approvato."],
    a: ["Amplification agent", "Agente amplificazione"],
    ad: "Customer Journey Analytics · GenStudio insights",
    op: "Social analytics + rules engine",
    tr: ["Organic performance crosses the bar.", "La performance organica supera la soglia."],
    do: ["Scores content, proposes or applies boosts by rule.", "Valuta i contenuti, propone o applica le spinte secondo regole."],
    out: ["Amplify list.", "Lista di amplificazione."],
    gate: ["Social lead sets the bar and budget cap.", "Il social lead fissa soglia e tetto di budget."],
    it: { r: "Spingere qualsiasi cosa sia uscita lunedì.", lad: ["Un'intuizione.", "I vincitori sono ordinati. Una persona conferma la spesa.", "Una regola spinge sopra la soglia."], h: "Il social lead fissa la soglia.", n: "Gli apprendimenti tornano comunque a Learn. Qui si spende e basta." }
  },
  "act::job::search": {
    l: ["Search ads from approved lines.", "Annunci search da testi approvati."],
    b: ["The agent builds responsive search ads from the copy deck and claims. The buyer sets match types and new themes.", "L'agente costruisce annunci search responsive dal copy deck e dai claim. Il buyer imposta corrispondenze e nuovi temi."],
    a: ["Search agent", "Agente search"],
    ad: "GenStudio for Performance Marketing · Adobe Advertising",
    op: "Search platform APIs",
    tr: ["Bookings include search.", "Le prenotazioni includono search."],
    do: ["Generates ad copy and extensions within claims.", "Genera testi ed estensioni entro i claim."],
    out: ["Search set.", "Set search."],
    gate: ["Search buyer on new themes.", "Il search buyer sui nuovi temi."],
    it: { r: "Una riscrittura freelance dentro l'account.", lad: ["Ogni RSA viene inventato.", "Testi dal pack. Il buyer imposta le corrispondenze.", "Le query note girano."], h: "Search buyer sui nuovi temi.", n: "La SEO sta in Owned. Qui si parla solo di intento a pagamento." }
  },
  "act::job::programmatic": {
    l: ["Programmatic lines built from the book.", "Linee programmatic costruite dalle prenotazioni."],
    b: ["The agent sets up lines, creatives and audiences from the booking. The trader confirms before go-live.", "L'agente configura linee, creatività e pubblici dalla prenotazione. Il trader conferma prima del go-live."],
    a: ["Programmatic agent", "Agente programmatic"],
    ad: "Adobe Advertising DSP · Real-Time CDP destinations",
    op: "DSP APIs + CDP",
    tr: ["Bookings include programmatic.", "Le prenotazioni includono programmatic."],
    do: ["Creates lines and trafficking from the placement set.", "Crea linee e trafficking dal set di placement."],
    out: ["Programmatic set.", "Set programmatic."],
    gate: ["Trader confirms.", "Il trader conferma."],
    it: { r: "Una campagna DSP costruita con i tag dell'anno scorso.", lad: ["Un trader ricostruisce ogni linea.", "Linee dalle prenotazioni. Il trader conferma.", "Always-on dopo un template."], h: "Trader.", n: "Il retail media è separato. Non nasconderlo dentro il display." }
  },
  "act::job::retail-affiliate": {
    l: ["Partners get the right kit and rules.", "I partner ricevono kit e regole giusti."],
    b: ["The agent packages assets, offers and rules for each partner. The partner lead approves before release.", "L'agente prepara asset, offerte e regole per ogni partner. Il partner lead approva prima del rilascio."],
    a: ["Partner kit agent", "Agente kit partner"],
    ad: "AEM Assets (Content Hub / brand portal)",
    op: "Brand portal + partner platform",
    tr: ["Partner is in the plan.", "Il partner è nel piano."],
    do: ["Builds partner kits, checks offer usage.", "Prepara i kit partner, verifica l'uso delle offerte."],
    out: ["Partner set.", "Set partner."],
    gate: ["Partnership / affiliate lead approves.", "Il partnership / affiliate lead approva."],
    it: { r: "Un affiliato che scrive la propria offerta.", lad: ["Ogni partner è un caso a sé.", "Kit più regole. Il partner lead approva.", "I partner noti scaricano il pack."], h: "Partnership / affiliate lead.", n: "I creator che servono un'idea nuova vanno a Routes. Gli amplificatori restano qui." }
  },
  "act::job::site-seo": {
    l: ["The campaign live on site, findable by search and AI.", "La campagna online sul sito, trovabile da search e AI."],
    b: ["The agent publishes pages from the pack, checks SEO and fixes issues. It also checks how AI assistants describe the offer.", "L'agente pubblica le pagine dal pack, verifica la SEO e corregge i problemi. Controlla anche come gli assistenti AI descrivono l'offerta."],
    a: ["Site optimisation agent", "Agente ottimizzazione sito"],
    ad: "AEM Sites · Sites Optimizer (Site Optimization Agent) · LLM Optimizer",
    op: "CMS + SEO and GEO tooling",
    tr: ["Page copy is locked.", "I testi delle pagine sono bloccati."],
    do: ["Publishes, audits SEO / performance, monitors AI-search visibility.", "Pubblica, verifica SEO e performance, monitora la visibilità nella ricerca AI."],
    out: ["Live page with issue log.", "Pagina online con log dei problemi."],
    gate: ["Web / SEO lead approves fixes.", "Il web / SEO lead approva le correzioni."],
    it: { r: "Una landing page con un altro tono.", lad: ["Il team web inventa un titolo.", "Il pack pubblica. La SEO controlla.", "Modelli di pagina noti."], h: "Web / SEO lead.", n: "La search a pagamento sta in Paid. Qui è traffico organico." }
  },
  "act::job::email-crm": {
    l: ["The inbox in step with the campaign.", "La casella email al passo con la campagna."],
    b: ["The agent builds emails and lifecycle steps from journey copy and segments. The CRM lead sequences and approves.", "L'agente costruisce email e step di lifecycle da testi journey e segmenti. Il CRM lead definisce la sequenza e approva."],
    a: ["CRM agent", "Agente CRM"],
    ad: "Journey Optimizer (AI assistant) · Real-Time CDP",
    op: "Marketing automation + CDP",
    tr: ["Journey copy and audiences exist.", "Esistono testi journey e pubblici."],
    do: ["Builds messages, send-time and test variants.", "Costruisce messaggi, orari di invio e varianti di test."],
    out: ["Live journeys.", "Journey attivi."],
    gate: ["CRM lead approves new journeys.", "Il CRM lead approva i nuovi journey."],
    it: { r: "Una mail di lifecycle che ignora la campagna.", lad: ["Il CRM scrive da zero.", "Testi dal pack. Il CRM lead definisce la sequenza.", "Step di servizio dopo un template."], h: "CRM lead.", n: "Orchestrate gestisce i tempi tra canali. Questo gestisce la casella email." }
  },
  "act::job::facelift": {
    l: ["Approved refreshes mid-flight.", "Aggiornamenti approvati a campagna in corso."],
    b: ["When content fatigues, the agent proposes approved swaps from the hub pack. Brand checks before it goes live.", "Quando un contenuto si consuma, l'agente propone sostituzioni approvate dal pack hub. Il brand controlla prima della pubblicazione."],
    a: ["Refresh agent", "Agente refresh"],
    ad: "AEM Sites · Adobe Target · GenStudio",
    op: "CMS + testing platform",
    tr: ["Fatigue or friction signal.", "Segnale di stanchezza o attrito."],
    do: ["Proposes swaps from approved modules.", "Propone sostituzioni da moduli approvati."],
    out: ["Swap list.", "Lista di sostituzioni."],
    gate: ["Brand plus digital lead approve.", "Brand e digital lead approvano."],
    it: { r: "Lanciare in silenzio la campagna due alla terza settimana.", lad: ["Qualcuno “aggiorna solo il banner”.", "Hub offre una sostituzione. Il brand controlla.", "Solo una lista di sostituzioni firmata."], h: "Brand e digital lead.", n: "L'hygiene può fornire il file. Il facelift decide se va online." }
  },
  "act::job::journeys": {
    l: ["The cross-channel path, designed once.", "Il percorso tra canali, progettato una volta."],
    b: ["The journey agent drafts the orchestration from the moment map: triggers, waits, channels. The journey lead edits and publishes.", "Il journey agent propone l'orchestrazione dalla mappa dei momenti: trigger, attese, canali. Il journey lead modifica e pubblica."],
    a: ["Journey agent", "Agente journey"],
    ad: "AJO Journey Agent",
    op: "Journey orchestration platform",
    tr: ["Moment map and content are ready.", "Mappa dei momenti e contenuti sono pronti."],
    do: ["Builds the journey in natural language, checks conflicts.", "Costruisce il journey in linguaggio naturale, verifica i conflitti."],
    out: ["Journey map ready to publish.", "Journey pronto per la pubblicazione."],
    gate: ["Journey lead publishes.", "Il journey lead pubblica."],
    it: { r: "Sperare che i canali si accorgano l'uno dell'altro.", lad: ["Una slide.", "Una mappa dal pack. Il lead modifica.", "Solo journey standard."], h: "Journey lead.", n: "La personalizzazione viene dopo. Questa è la spina dorsale." }
  },
  "act::job::personalization": {
    l: ["The right approved variant for each audience.", "La variante approvata giusta per ogni pubblico."],
    b: ["Rules and models pick approved modules, offers and language per audience. People set the rulebook.", "Regole e modelli scelgono moduli, offerte e lingua approvati per ogni pubblico. Le persone scrivono il regolamento."],
    a: ["Personalisation agent", "Agente personalizzazione"],
    ad: "Adobe Target · AEP Experimentation Agent · Real-Time CDP",
    op: "Testing & personalisation platform",
    tr: ["Visitor or customer matches an audience.", "Un visitatore o cliente rientra in un pubblico."],
    do: ["Selects variants, runs tests, proposes new experiments.", "Sceglie le varianti, esegue test, propone nuovi esperimenti."],
    out: ["Personalisation set.", "Set di personalizzazione."],
    gate: ["Activation lead owns the rulebook.", "L'activation lead è responsabile del regolamento."],
    it: { r: "Un messaggio one-to-one che ha saltato la revisione legale.", lad: ["Ogni utente è un workshop.", "Le regole scelgono i moduli. Una persona scrive la regola.", "Le regole note girano."], h: "L'activation lead definisce il regolamento.", n: "I nuovi moduli si creano in Hub prima di entrare nella personalizzazione." }
  },
  "act::job::in-flight": {
    l: ["Adjust while it runs, inside the envelope.", "Correggere mentre gira, entro i limiti concordati."],
    b: ["The agent reads pacing, winners and friction signals and proposes moves. Moves inside the signed envelope run; the rest wait.", "L'agente legge segnali di pacing, contenuti migliori e attriti e propone interventi. Gli interventi entro i limiti firmati partono; gli altri aspettano."],
    a: ["In-flight agent", "Agente in-flight"],
    ad: "Customer Journey Analytics",
    op: "Agent orchestration + analytics",
    tr: ["Signal crosses a threshold.", "Un segnale supera una soglia."],
    do: ["Diagnoses, proposes, applies allowed moves, logs everything.", "Diagnostica, propone, applica gli interventi consentiti, registra tutto."],
    out: ["In-flight log.", "Log in-flight."],
    gate: ["Activation lead on anything that changes spend or claim.", "L'activation lead su tutto ciò che cambia spesa o claim."],
    it: { r: "Una ricostruzione silenziosa alla seconda settimana.", lad: ["Modifiche nel panico.", "I segnali propongono. Una persona conferma.", "Regole dentro limiti firmati."], h: "L'activation lead su tutto ciò che cambia spesa o claim.", n: "Activation aggiorna il passaggio a Learn per tutta la durata della campagna." }
  },
  "act::job::launch-gates": {
    l: ["Every named approver says yes.", "Ogni approvatore designato dice sì."],
    b: ["The agent collects the evidence for each gate and routes it to the people named in Demand. Only they can sign.", "L'agente raccoglie le evidenze per ogni gate e le invia alle persone indicate in Demand. Solo loro possono firmare."],
    a: ["Gatekeeper agent", "Agente gatekeeper"],
    ad: "Workfront approvals",
    op: "Work-management approvals",
    tr: ["Live set is ready.", "Il set online è pronto."],
    do: ["Builds the gate checklist, chases signatures, logs the audit trail.", "Prepara la checklist del gate, sollecita le firme, registra l'audit trail."],
    out: ["Gate log.", "Log dei gate."],
    gate: ["Each named approver signs.", "Ogni approvatore designato firma."],
    it: { r: "Un pollice in su in chat.", lad: ["Chi è online.", "La mappa da Demand. Le persone firmano.", "Mai la firma."], h: "Ogni approvatore designato.", n: "Demand li ha già nominati. Questa funzione raccoglie solo il sì." }
  },
  "act::job::brand-control": {
    l: ["What is live matches what was approved.", "Ciò che è online corrisponde a ciò che è stato approvato."],
    b: ["The agent checks live ads, pages and partner placements against the pack and flags drift. Brand signs off the live set.", "L'agente verifica annunci, pagine e placement dei partner online rispetto al pack e segnala gli scostamenti. Il brand firma il set online."],
    a: ["Live brand agent", "Agente brand online"],
    ad: "Adobe Brand Intelligence · Sites Optimizer",
    op: "Brand compliance AI + crawler",
    tr: ["Go-live and every in-flight change.", "Go-live e ogni modifica in corso."],
    do: ["Crawls placements, compares to masters, flags breaks.", "Scansiona i placement, li confronta con i master, segnala le violazioni."],
    out: ["Live QA report.", "Report di QA online."],
    gate: ["Brand signs.", "Il brand firma."],
    it: { r: "Un partner che va online con l'offerta sbagliata.", lad: ["Qualcuno “dà un'occhiata”.", "Segnalazioni rispetto al pack. Il brand firma.", "Solo violazioni note."], h: "Brand.", n: "Il QA di produzione ha firmato i master. Questo firma il set online." }
  },
  "act::job::handoff-to-learn": {
    l: ["Delivery data handed to Learn, automatically.", "I dati di consegna passano a Learn, in automatico."],
    b: ["At go-live and at every change the agent records what ran, where, when and for how much, matched to the learning slots.", "Al go-live e a ogni modifica l'agente registra cosa è andato online, dove, quando e con quale budget, collegandolo agli slot di apprendimento."],
    a: ["Handoff agent", "Agente handoff"],
    ad: "AEP · Customer Journey Analytics",
    op: "Data pipeline + BI",
    tr: ["Go-live and every in-flight change.", "Go-live e ogni modifica in corso."],
    do: ["Assembles the learn packet, checks completeness.", "Assembla il learn packet, verifica la completezza."],
    out: ["Learn packet.", "Learn packet."],
    gate: ["Analytics lead confirms completeness.", "L'analytics lead conferma la completezza."],
    it: { r: "Una slide di wash-up.", lad: ["Qualcuno inoltra una cartella.", "Il packet si assembla. L'analista conferma.", "Il packet si scrive da solo al go-live e a ogni modifica."], h: "L'analytics lead conferma la completezza.", n: "Activation registra i dati di consegna, così Learn lavora sullo stesso record." }
  }
});
