/* Creative Production — job enrichment (EN / IT). See content-intel.js for keys. */
window.CONTENT = window.CONTENT || {};
Object.assign(window.CONTENT, {
  "make::job::route-scamps": {
    l: ["Creative routes from the signed brief.", "Le route creative dal brief firmato."],
    b: ["The agency creates the routes. The agent lays out references, constraints and comparable past work so the decision meeting has a clear basis.", "Le route le crea l'agenzia. L'agente prepara riferimenti, vincoli e lavori passati comparabili, così la riunione decisionale ha una base chiara."],
    a: ["Route-prep agent", "Agente preparazione route"],
    ad: "AEM Assets",
    op: "DAM + collaboration board",
    tr: ["Brief is signed.", "Il brief è firmato."],
    do: ["Gathers references and checks each route against the brief.", "Raccoglie riferimenti e verifica ogni route rispetto al brief."],
    out: ["Route decision pack.", "Pack decisionale delle route."],
    gate: ["Lead agency creative owns route generation.", "Il creativo dell'agenzia è responsabile delle route."],
    it: { r: "Dodici territori e una presentazione di tre ore.", lad: ["Il team inventa su una parete.", "L'agente prepara le opzioni. Il mestiere resta umano.", "La generazione delle route resta all'agenzia creativa."], h: "Il creativo dell'agenzia è responsabile della generazione delle route.", n: "Se manca il brief, si ferma. Non inventa una route." }
  },
  "make::job::territory-lock": {
    l: ["One route chosen for production.", "Una sola route scelta per la produzione."],
    b: ["Brand and the lead creative approve one route. Hero, Copy, Hub and QA all build on that decision.", "Brand e direzione creativa approvano una route. Hero, Copy, Hub e QA partono tutti da quella decisione."],
    a: ["Decision recorder", "Registratore di decisioni"],
    ad: "Workfront approvals",
    op: "Work-management approvals",
    tr: ["Route pack is presented.", "Il pack delle route è presentato."],
    do: ["Records the decision, rationale and signatories.", "Registra decisione, motivazione e firmatari."],
    out: ["Locked territory on the record.", "Territorio bloccato sul record."],
    gate: ["Brand and ECD sign the lock.", "Brand ed ECD firmano il blocco."],
    it: { r: "Fondere due route in ascensore dopo la riunione.", lad: ["Brand ed ECD decidono.", "Le opzioni sono visibili. Il blocco è una persona.", "Mai."], h: "Brand e direzione creativa approvano il blocco per la produzione.", n: "Il work management registra il blocco firmato del territorio." }
  },
  "make::job::art-direction": {
    l: ["The visual rules for the chosen route.", "Le regole visive per la route scelta."],
    b: ["The art director sets colour, type, image and motion rules. The agent compiles references into a reusable pack.", "L'art director definisce colori, font, immagini e motion. L'agente raccoglie i riferimenti in un pack riutilizzabile."],
    a: ["Art-direction pack agent", "Agente pack art direction"],
    ad: "Adobe Brand Intelligence · AEM Assets · Firefly custom models",
    op: "DAM + brand portal",
    tr: ["Territory is locked.", "Il territorio è bloccato."],
    do: ["Compiles references, tags rules, prepares style guidance for generators.", "Raccoglie riferimenti, tagga le regole, prepara le guide di stile per i generatori."],
    out: ["Art-direction pack.", "Pack di art direction."],
    gate: ["Art director approves.", "L'art director approva."],
    it: { r: "“Fallo premium.”", lad: ["L'art director lo scrive su un tovagliolo.", "L'agente raccoglie riferimenti. Il mestiere guida.", "Il sistema assembla il pack; il giudizio creativo resta al team."], h: "L'art director dell'agenzia creativa del cliente.", n: "Le declinazioni possono usare questo pack. Non possono inventarne uno nuovo." }
  },
  "make::job::hero-still": {
    l: ["The campaign's key image.", "L'immagine chiave della campagna."],
    b: ["The agency shoots or commissions the hero image. Agents only prepare casting, references and the call sheet.", "L'agenzia scatta o commissiona l'immagine hero. Gli agenti preparano solo casting, riferimenti e call sheet."],
    a: ["Production-prep agent", "Agente pre-produzione"],
    ad: "Workfront · AEM Assets",
    op: "Production management + DAM",
    tr: ["Art-direction pack is approved.", "Il pack di art direction è approvato."],
    do: ["Prepares logistics, rights checks and asset ingestion.", "Prepara logistica, verifica diritti e caricamento degli asset."],
    out: ["Hero still in the DAM with rights metadata.", "Hero still nel DAM con metadati sui diritti."],
    gate: ["Art director owns the picture.", "L'art director è responsabile dell'immagine."],
    it: { r: "Un'immagine stock che “cambiamo dopo”.", lad: ["Fotografo / art director.", "Casting, riferimenti, call sheet.", "Mai l'immagine in sé."], h: "L'art director guida la Hero.", n: "Hub e declinazioni possono ritagliarla. Non possono sostituirla." }
  },
  "make::job::hero-film": {
    l: ["The campaign film.", "Il film della campagna."],
    b: ["The agency and production partners make the film. Agents prepare boards, specs and the claim pack, and ingest the masters.", "Agenzia e casa di produzione realizzano il film. Gli agenti preparano board, specifiche e pack claim, e caricano i master."],
    a: ["Production-prep agent", "Agente pre-produzione"],
    ad: "Workfront · Frame.io · AEM Assets",
    op: "Production management + review + DAM",
    tr: ["Script and art direction are approved.", "Script e art direction sono approvati."],
    do: ["Tracks versions, collects review comments, checks deliverables.", "Traccia le versioni, raccoglie i commenti, verifica i deliverable."],
    out: ["Approved film masters.", "Master del film approvati."],
    gate: ["Director and producer own the film.", "Regista e producer sono responsabili del film."],
    it: { r: "Un taglio da 15 secondi fatto prima che qualcuno approvasse l'idea.", lad: ["Regista e producer.", "Board, specifiche, pack claim.", "Mai il film. I cutdown arrivano dopo, in Activation."], h: "Agenzia principale / casa di produzione.", n: "Activation può accorciarlo. Non può inventare una nuova hero." }
  },
  "make::job::master-line": {
    l: ["The line the campaign stands on.", "La frase su cui si regge la campagna."],
    b: ["A writer crafts the master line from the locked offer and allowed claims. Agents show what is allowed, never write it.", "Un copywriter scrive la master line dall'offerta bloccata e dai claim ammessi. Gli agenti mostrano cosa è consentito, non la scrivono mai."],
    a: ["Claims guard", "Guardiano dei claim"],
    ad: "Adobe Brand Intelligence",
    op: "Claims register + brand portal",
    tr: ["Territory and offer are locked.", "Territorio e offerta sono bloccati."],
    do: ["Checks candidate lines against claims and red lines.", "Verifica le frasi candidate rispetto a claim e linee rosse."],
    out: ["Compliance flags on candidates.", "Segnalazioni di conformità sulle candidate."],
    gate: ["Copywriter, signed with the territory.", "Il copywriter, firmata insieme al territorio."],
    it: { r: "Cinque headline e nessuna campagna.", lad: ["Un copywriter dell'agenzia creativa del cliente.", "Claim ammessi e tensioni sono sulla pagina.", "No."], h: "Il copywriter. Firmata con il territorio.", n: "Se questa frase cambia, Hub e declinazioni si fermano finché non viene bloccata di nuovo." }
  },
  "make::job::headlines-lines": {
    l: ["Headlines that extend the master line.", "Headline che estendono la master line."],
    b: ["The agent drafts headline sets from the master line and the claim library. The writer edits and locks.", "L'agente propone set di headline dalla master line e dalla libreria claim. Il copywriter modifica e blocca."],
    a: ["Copy agent", "Agente copy"],
    ad: "GenStudio for Performance Marketing · Brand Intelligence",
    op: "Brand-tuned LLM + claims register",
    tr: ["Master line is locked.", "La master line è bloccata."],
    do: ["Generates variants per channel and length, scored for brand fit.", "Genera varianti per canale e lunghezza, con punteggio di aderenza al brand."],
    out: ["Headline set.", "Set di headline."],
    gate: ["Copywriter locks.", "Il copywriter blocca."],
    it: { r: "Un foglio di calcolo pieno di giochi di parole.", lad: ["Il copywriter parte da zero.", "Bozze dalla master line e dalla libreria. Il copywriter blocca.", "Solo quando la frase è bloccata e il claim è consolidato."], h: "Copywriter.", n: "Hub può riusarle. Le declinazioni possono accorciarle. Nessuno può riscrivere la promessa." }
  },
  "make::job::scripts-vo": {
    l: ["Timed scripts and voice-over.", "Script e voice-over a tempo."],
    b: ["The agent drafts timed scripts from the line and the copy deck. The writer edits every word that goes on air.", "L'agente propone script a tempo dalla master line e dal copy deck. Il copywriter rivede ogni parola che va in onda."],
    a: ["Script agent", "Agente script"],
    ad: "GenStudio · Brand Intelligence",
    op: "Brand-tuned LLM",
    tr: ["Copy deck exists.", "Esiste il copy deck."],
    do: ["Drafts versions to time, flags claim and disclaimer needs.", "Propone versioni a tempo, segnala esigenze di claim e disclaimer."],
    out: ["Script drafts.", "Bozze di script."],
    gate: ["Copywriter / agency edits.", "Copywriter / agenzia modificano."],
    it: { r: "Una voice-over scritta il giorno delle riprese.", lad: ["Un copywriter in sala di registrazione.", "Bozze a tempo dalla frase. Il copywriter modifica.", "Nessuno script nuovo da un prompt."], h: "Copywriter / agenzia.", n: "Il film hero lo usa. I cutdown in Activation possono solo accorciare." }
  },
  "make::job::disclaimers": {
    l: ["The right small print, every time.", "Le note legali giuste, ogni volta."],
    b: ["Cleared disclaimers attach themselves to every asset that carries a claim. A new one raises a legal gate.", "I disclaimer approvati si allegano da soli a ogni asset che contiene un claim. Uno nuovo apre un gate legale."],
    a: ["Disclaimer agent", "Agente disclaimer"],
    ad: "Adobe Brand Intelligence · GenStudio",
    op: "Claims register + rules engine",
    tr: ["Any asset carries a claim.", "Un asset contiene un claim."],
    do: ["Matches claim to disclaimer by market and format.", "Abbina claim e disclaimer per mercato e formato."],
    out: ["Disclaimer set.", "Set di disclaimer."],
    gate: ["Legal reviews anything new.", "Il legale rivede ogni novità."],
    it: { r: "Il legale che trova l'asterisco mancante all'ultima review.", lad: ["Il legale li riscrive ogni volta.", "Le frasi note si allegano. Quelle nuove aprono un gate.", "Le frasi approvate si allegano da sole."], h: "Il legale rivede i claim fuori dalla libreria attuale.", n: "Declinazioni e formati devono riportarli. Non possono nasconderli." }
  },
  "make::job::page-copy": {
    l: ["Web pages in the campaign's voice.", "Pagine web con la voce della campagna."],
    b: ["The agent drafts page copy from the brief pack and proof. The content editor locks before it reaches the CMS.", "L'agente propone i testi delle pagine da brief e prove. Il content editor blocca prima che arrivino nel CMS."],
    a: ["Page copy agent", "Agente testi pagina"],
    ad: "AEM Sites (Generate Variations) · GenStudio for Content Marketing",
    op: "CMS with gen-AI authoring",
    tr: ["Master line and offer are locked.", "Master line e offerta sono bloccate."],
    do: ["Drafts modules, metadata and answer-ready content for AI search.", "Propone moduli, metadati e contenuti pronti per la ricerca AI."],
    out: ["Page copy in the CMS draft.", "Testi pagina in bozza nel CMS."],
    gate: ["Content editor locks.", "Il content editor blocca."],
    it: { r: "Lorem ipsum e un ritaglio della hero.", lad: ["Il team web scrive da zero.", "Bozza dal pack del brief. L'editor blocca.", "Solo dopo che il modello di pagina è collaudato."], h: "Content editor.", n: "Activation può personalizzare i moduli. Non può cambiare la promessa." }
  },
  "make::job::journey-copy": {
    l: ["Lifecycle messages that match the campaign.", "Messaggi di lifecycle coerenti con la campagna."],
    b: ["The agent drafts emails, push and in-app messages per moment. The CRM lead edits and keeps the tone.", "L'agente propone email, push e messaggi in-app per ogni momento. Il CRM lead modifica e mantiene il tono."],
    a: ["Journey copy agent", "Agente testi journey"],
    ad: "Journey Optimizer AI assistant · GenStudio",
    op: "Marketing automation + LLM",
    tr: ["Moment map exists.", "Esiste la mappa dei momenti."],
    do: ["Drafts copy per step and audience, within claims.", "Propone testi per step e pubblico, entro i claim."],
    out: ["Journey copy.", "Testi journey."],
    gate: ["CRM / journey lead edits.", "Il CRM / journey lead modifica."],
    it: { r: "Una mail di lifecycle che ignora la campagna.", lad: ["Il CRM scrive con un altro tono.", "Bozze dalla frase. Il CRM lead modifica.", "Solo step di servizio."], h: "CRM / journey lead.", n: "L'orchestrazione vive in Activation. I testi si fanno qui." }
  },
  "make::job::document-copy": {
    l: ["Brochures, FAQs and documents.", "Brochure, FAQ e documenti."],
    b: ["Agents gather sources and prior approved text. Content and legal write, because documents carry commitments.", "Gli agenti raccolgono fonti e testi già approvati. Contenuti e legale scrivono, perché i documenti contengono impegni."],
    a: ["Source agent", "Agente fonti"],
    ad: "GenStudio for Content Marketing · AEM Assets",
    op: "Document store + LLM",
    tr: ["Product truth and proof are ready.", "Product truth e prove sono pronte."],
    do: ["Collects sources, prior versions and mandatory clauses.", "Raccoglie fonti, versioni precedenti e clausole obbligatorie."],
    out: ["Source pack for writers.", "Pack di fonti per chi scrive."],
    gate: ["Content plus legal write and sign.", "Contenuti e legale scrivono e firmano."],
    it: { r: "Un PDF dell'anno scorso con una nuova copertina.", lad: ["Scrivono legale e contenuti.", "Le fonti sono raccolte. Scrivono le persone.", "No."], h: "Contenuti e legale.", n: "Più vicino alla hero che a un ritaglio. Più lontano di un film. Comunque non è hygiene." }
  },
  "make::job::series-extensions": {
    l: ["More pieces from the same idea.", "Più contenuti dalla stessa idea."],
    b: ["The agent proposes a series from the hero pack and generates first variants. The studio crafts the final pieces.", "L'agente propone una serie dal pack hero e genera le prime varianti. Lo studio rifinisce i pezzi finali."],
    a: ["Variant agent", "Agente varianti"],
    ad: "Firefly Creative Production · GenStudio for Performance Marketing",
    op: "Commercially safe gen-AI + template studio",
    tr: ["Hero pack is approved.", "Il pack hero è approvato."],
    do: ["Generates on-brand extensions within the art-direction pack.", "Genera estensioni on-brand entro il pack di art direction."],
    out: ["Series set for review.", "Set della serie per la revisione."],
    gate: ["Studio lead approves.", "Lo studio lead approva."],
    it: { r: "Una nuova route ogni giovedì.", lad: ["Ogni pezzo è un nuovo brief.", "Serie proposta dalla hero. Lo studio realizza.", "Solo lavori su pattern collaudati."], h: "Studio lead.", n: "Se serve un'idea nuova, non è Hub. Torna a Routes." }
  },
  "make::job::always-on": {
    l: ["Everyday content from approved templates.", "Contenuti quotidiani da template approvati."],
    b: ["Agents fill approved templates with product and copy. A human checks before anything goes into the DAM.", "Gli agenti compilano template approvati con prodotto e testi. Una persona controlla prima che qualcosa entri nel DAM."],
    a: ["Template agent", "Agente template"],
    ad: "GenStudio for Performance Marketing · Firefly",
    op: "Template studio + gen-AI",
    tr: ["Template is signed.", "Il template è firmato."],
    do: ["Produces template-based assets at volume.", "Produce asset da template in volume."],
    out: ["Always-on set.", "Set always-on."],
    gate: ["In-house studio checks.", "Lo studio interno controlla."],
    it: { r: "Un banner fatto di corsa con il font sbagliato.", lad: ["Qualcuno “lo butta giù”.", "Template dal pack. Una persona controlla.", "Una volta firmato il template."], h: "Studio interno.", n: "Più vicino all'hygiene che alla hero. Comunque si fa qui, non in Activation." }
  },
  "make::job::dam-pull": {
    l: ["Reuse what you already own.", "Riutilizzare ciò che si ha già."],
    b: ["The agent searches the DAM against the approved art direction and rights, and ranks what can be reused.", "L'agente cerca nel DAM in base all'art direction approvata e ai diritti, e ordina ciò che può essere riutilizzato."],
    a: ["Asset discovery agent", "Agente ricerca asset"],
    ad: "AEM Assets (smart tags, content intelligence)",
    op: "DAM with AI search",
    tr: ["Art-direction pack exists.", "Esiste il pack di art direction."],
    do: ["Semantic search, rights and expiry check, ranking.", "Ricerca semantica, verifica diritti e scadenze, ordinamento."],
    out: ["Asset shortlist.", "Shortlist di asset."],
    gate: ["Studio / DAM owner on untagged items.", "Studio / owner del DAM sugli asset non taggati."],
    it: { r: "Un designer che cerca cartelle chiamate FINAL_v7.", lad: ["Qualcuno si ricorda di uno shooting.", "Ricerca ordinata. Una persona sceglie.", "Gli asset approvati si allegano da soli."], h: "Studio / owner del DAM per tutto ciò che non è taggato.", n: "Il punto più automatizzato della produzione prima di Activation." }
  },
  "make::job::brand-qa": {
    l: ["Is it on brand? Checked, not guessed.", "È on brand? Verificato, non a occhio."],
    b: ["The agent checks every asset against brand codes, claims and red lines and explains each flag. Brand signs.", "L'agente verifica ogni asset rispetto a codici di brand, claim e linee rosse e spiega ogni segnalazione. Il brand firma."],
    a: ["Brand check agent", "Agente controllo brand"],
    ad: "Adobe Brand Intelligence · Workfront proofing",
    op: "Brand compliance AI + proofing",
    tr: ["Asset is submitted for review.", "Un asset viene inviato in revisione."],
    do: ["Scores brand fit, flags code breaks and risky claims.", "Valuta l'aderenza al brand, segnala violazioni e claim rischiosi."],
    out: ["Brand QA report.", "Report di brand QA."],
    gate: ["Brand signs; taste stays human.", "Il brand firma; il gusto resta umano."],
    it: { r: "Un like su un link di anteprima.", lad: ["Qualcuno “dà un'occhiata”.", "Segnalazioni rispetto al pack. Il brand firma.", "Solo violazioni note."], h: "Brand.", n: "Le violazioni dei codici generano una segnalazione; il gusto resta un giudizio creativo." }
  },
  "make::job::spec-qa": {
    l: ["Files that pass media specs first time.", "File che passano le specifiche media al primo colpo."],
    b: ["The agent checks formats, sizes, lengths, safe areas and accessibility before anything ships.", "L'agente controlla formati, dimensioni, durate, safe area e accessibilità prima di qualsiasi uscita."],
    a: ["Spec check agent", "Agente controllo specifiche"],
    ad: "GenStudio for Performance Marketing (channel validation)",
    op: "Automated preflight",
    tr: ["Asset enters the master pack.", "L'asset entra nel master pack."],
    do: ["Runs the channel checklist, lists failures.", "Esegue la checklist di canale, elenca gli errori."],
    out: ["Spec QA log.", "Log di spec QA."],
    gate: ["Producer only on failures.", "Il producer interviene solo sugli errori."],
    it: { r: "Il media che rifiuta il file il venerdì sera.", lad: ["Qualcuno apre il file.", "I controlli girano. Gli errori sono elencati.", "La checklist gira da sola."], h: "Il producer interviene solo sugli errori.", n: "Activation lo rieseguirà sulle declinazioni." }
  },
  "make::job::master-pack": {
    l: ["The signed package Activation works from.", "Il pacchetto firmato da cui lavora Activation."],
    b: ["The agent assembles masters, copy, claims and rights into one pack. Producer and brand sign it.", "L'agente assembla master, testi, claim e diritti in un unico pack. Producer e brand lo firmano."],
    a: ["Pack compiler", "Compilatore del pack"],
    ad: "AEM Assets collections · Workfront approvals",
    op: "DAM + work-management approvals",
    tr: ["Brand and spec QA are green.", "Brand e spec QA sono verdi."],
    do: ["Assembles, versions and checks completeness.", "Assembla, versiona e verifica la completezza."],
    out: ["Master pack ready for signature.", "Master pack pronto per la firma."],
    gate: ["Producer plus brand sign.", "Producer e brand firmano."],
    it: { r: "Uno zip chiamato FINAL_USE_THIS.", lad: ["Un producer manda una cartella via email.", "Il pack è assemblato. Una persona firma.", "Solo l'assemblaggio. La firma è umana."], h: "Producer e brand.", n: "Il compilatore. Non produce nulla se Routes, Hero o QA sono aperti." }
  }
});
