/* Strategic Intelligence — job enrichment (EN / IT).
   Keys: l lede · b body · a agent · ad Adobe CX Enterprise example · op open-stack equivalent
         tr trigger · do what the agent does · out output · gate human gate
         n  EN notes override · it Italian for replaces / ladder / human / notes */
window.CONTENT = window.CONTENT || {};
Object.assign(window.CONTENT, {
  "intel::job::request-intake": {
    l: ["Any request becomes a structured mandate.", "Ogni richiesta diventa un mandato strutturato."],
    b: ["The intake agent reads the email, chat or form, fills the mandate fields and opens one record in work management.", "L'agente di intake legge email, chat o form, compila i campi del mandato e apre un unico record nel work management."],
    a: ["Intake agent", "Agente di intake"],
    ad: "Adobe Marketing Agent for Microsoft 365 Copilot · Workfront",
    op: "Enterprise AI assistant + work-management API",
    tr: ["A request lands in Copilot, Teams, email or a form.", "Arriva una richiesta da Copilot, Teams, email o form."],
    do: ["Extracts requester, market, objective, timing and budget; asks only for what is missing.", "Estrae richiedente, mercato, obiettivo, tempi e budget; chiede solo ciò che manca."],
    out: ["Mandate stub in the queue.", "Bozza di mandato in coda."],
    gate: ["MarOps rejects junk or duplicates.", "MarOps scarta richieste duplicate o non valide."],
    it: { r: "Copiare l'ultimo brief e cambiare la data.", lad: ["Qualcuno ricopia la richiesta in un template.", "L'agente prepara la bozza. Una persona conferma i campi.", "Le richieste strutturate compaiono senza che nessuno tocchi il form."], h: "MarOps gestisce eccezioni e richieste non valide.", n: "Nessun agente a valle parte finché la bozza non ha un richiedente e un mercato." }
  },
  "intel::job::stakeholder-map": {
    l: ["Who decides, who reviews, who signs.", "Chi decide, chi rivede, chi firma."],
    b: ["The agent proposes the RACI from the last similar mandate and the people directory. The campaign lead confirms it.", "L'agente propone la RACI partendo dall'ultimo mandato simile e dalla directory aziendale. Il campaign lead la conferma."],
    a: ["Stakeholder agent", "Agente stakeholder"],
    ad: "Microsoft Graph · Workfront",
    op: "Identity directory + work-management roles",
    tr: ["Mandate stub is accepted.", "La bozza di mandato è accettata."],
    do: ["Matches roles to people, flags gaps and conflicting approvers.", "Associa ruoli e persone, segnala buchi e approvatori in conflitto."],
    out: ["RACI and approver list on the record.", "RACI e lista approvatori sul record."],
    gate: ["Campaign lead confirms before the brief runs.", "Il campaign lead conferma prima che parta il brief."],
    it: { r: "Chiedere in giro chi aveva firmato l'anno scorso.", lad: ["Il lead tiene i nomi in testa.", "L'agente propone la mappa dall'ultimo mandato simile. Una persona conferma.", "Il routing per ruolo compila la mappa. Le persone aggiungono solo le eccezioni."], h: "Il campaign lead conferma la mappa prima che parta il Brief.", n: "Legge gli oggetti stakeholder del Brain. Non inventa mai un nuovo ruolo di approvazione." }
  },
  "intel::job::priority-vs-calendar": {
    l: ["Rank the request against everything else.", "Dare priorità alla richiesta rispetto a tutto il resto."],
    b: ["The agent shows collisions with the calendar, capacity and budget. A named owner sets the priority.", "L'agente mostra le collisioni con calendario, capacità e budget. Un owner con nome e cognome decide la priorità."],
    a: ["Capacity agent", "Agente di capacità"],
    ad: "Workfront Workflow Optimization Agent",
    op: "Work-management capacity planning",
    tr: ["New mandate enters the queue.", "Un nuovo mandato entra in coda."],
    do: ["Simulates impact on calendar, people and running work; proposes a slot.", "Simula l'impatto su calendario, persone e attività in corso; propone uno slot."],
    out: ["Queue recommendation with trade-offs.", "Proposta di priorità con i trade-off."],
    gate: ["Head of Campaign or MarOps decides.", "Decide l'Head of Campaign o MarOps."],
    it: { r: "Tutto è P1 finché qualcosa non esce in ritardo.", lad: ["La priorità è di chi ha urlato per ultimo.", "Le collisioni sono visibili. Una persona decide l'ordine.", "Le policy possono rinviare i conflitti ovvi. Il lancio richiede sempre una persona."], h: "Head of Campaign o MarOps fissano la priorità finale.", n: "Si parte da qui. Nessuna attività strategica gira su un mandato senza priorità." }
  },
  "intel::job::platform-voice": {
    l: ["The right slice of the brand for this brief.", "La parte di brand giusta per questo brief."],
    b: ["Instead of the full brand book, the agent compiles the platform, tone and visual codes that apply to this mandate.", "Invece dell'intero brand book, l'agente raccoglie piattaforma, tono e codici visivi che valgono per questo mandato."],
    a: ["Brand codes agent", "Agente codici di brand"],
    ad: "Adobe Brand Intelligence",
    op: "Brand portal + governed brand knowledge base",
    tr: ["Mandate has a category and market.", "Il mandato ha categoria e mercato."],
    do: ["Retrieves current brand rules and examples; scopes them to the brief.", "Recupera regole ed esempi di brand aggiornati e li circoscrive al brief."],
    out: ["Scoped voice pack.", "Voice pack circoscritto."],
    gate: ["Brand manager signs when the category is new.", "Il brand manager firma se la categoria è nuova."],
    it: { r: "“Fallo on brand” come unica direzione creativa.", lad: ["Qualcuno incolla le frasi dell'anno scorso.", "L'agente prepara il pack. Il brand lo modifica.", "Il pack si compone dai file aggiornati. Serve una persona solo su territori nuovi."], h: "Il brand manager firma il pack quando il mandato entra in una nuova categoria.", n: "Non inventa mai una nuova frase. Se nel Brain non c'è una piattaforma, si ferma." }
  },
  "intel::job::claim-library": {
    l: ["Only claims that are already cleared.", "Solo claim già approvati."],
    b: ["The agent attaches the claims legal has already approved for this product and market. Anything new raises a gate.", "L'agente allega i claim già approvati dal legale per questo prodotto e mercato. Ogni claim nuovo apre un gate."],
    a: ["Claims agent", "Agente claim"],
    ad: "Adobe Brand Intelligence · AEM Assets",
    op: "Claims register + document store",
    tr: ["Product and market are known.", "Prodotto e mercato sono noti."],
    do: ["Matches the mandate to cleared claims and their validity dates.", "Abbina il mandato ai claim approvati e alle loro scadenze."],
    out: ["Allowed claims list (references).", "Elenco dei claim ammessi (riferimenti)."],
    gate: ["Legal reviews any claim outside the library.", "Il legale rivede ogni claim fuori libreria."],
    it: { r: "Un foglio Excel sul desktop di qualcuno.", lad: ["Il legale viene coinvolto quando il concept è già piaciuto.", "L'agente propone i claim ammessi. Il legale conferma quelli nuovi.", "I claim approvati si allegano in automatico. Quelli nuovi aprono un gate."], h: "Legale o brand rivedono i claim fuori dalla libreria attuale.", n: "Scrive solo riferimenti. Il claim vive nel Brain." }
  },
  "intel::job::do-nots": {
    l: ["The red lines, written down before work starts.", "Le linee rosse, scritte prima di iniziare."],
    b: ["The agent lists the known red lines for this market and topic. Comms and legal own every new one.", "L'agente elenca le linee rosse note per questo mercato e tema. Comunicazione e legale sono responsabili di ogni nuova linea."],
    a: ["Guardrails agent", "Agente guardrail"],
    ad: "Adobe Brand Intelligence",
    op: "Policy engine + collaboration",
    tr: ["Brief scope is defined.", "Il perimetro del brief è definito."],
    do: ["Collects applicable policies, sensitivities and past escalations.", "Raccoglie policy applicabili, sensibilità e escalation passate."],
    out: ["Red-line pack used by every later gate.", "Pack di linee rosse usato da tutti i gate successivi."],
    gate: ["Corporate comms and legal own the line.", "Comunicazione corporate e legale sono responsabili delle linee."],
    it: { r: "Una chiacchierata in corridoio dopo la prima review.", lad: ["I divieti vivono nei nervi delle persone.", "L'agente elenca le linee rosse note. Comunicazione e legale spuntano.", "Le linee rosse note si allegano da sole. Quelle nuove restano umane."], h: "Comunicazione corporate e legale. Sono loro a tracciare la linea.", n: "Le approvazioni applicano questo pack. Questo agente si limita a scriverlo." }
  },
  "intel::job::segment-evidence": {
    l: ["Who the audience is, from live data.", "Chi è il pubblico, dai dati reali."],
    b: ["The agent pulls current segment size, behaviour and value from the CDP and analytics, not from last year's deck.", "L'agente estrae dimensione, comportamento e valore dei segmenti da CDP e analytics, non dalla presentazione dell'anno scorso."],
    a: ["Audience agent", "Agente audience"],
    ad: "AEP Audience Agent · Real-Time CDP",
    op: "Customer data platform + web analytics",
    tr: ["Mandate has an objective and market.", "Il mandato ha obiettivo e mercato."],
    do: ["Finds matching segments, detects overlaps and size changes.", "Trova i segmenti adatti, rileva sovrapposizioni e variazioni di dimensione."],
    out: ["Segment evidence page.", "Pagina di evidenze sui segmenti."],
    gate: ["Insights confirms the cut when data conflicts.", "Insights conferma il taglio se i dati sono in conflitto."],
    it: { r: "La presentazione dell'anno scorso con una nuova copertina.", lad: ["Si allega un PDF di ricerca.", "L'agente compila i numeri aggiornati. Una persona sceglie il taglio.", "Le evidenze si aggiornano a ogni mandato."], h: "Insights o analytics confermano il taglio quando i dati sono in conflitto.", n: "Usa i segmenti già presenti nel Company Brain." }
  },
  "intel::job::tension-jtbd": {
    l: ["The human truth the work must answer.", "La verità umana a cui il lavoro deve rispondere."],
    b: ["From the evidence the agent drafts three candidate tensions. The strategist writes the one that matters.", "Partendo dalle evidenze l'agente propone tre tensioni candidate. Lo strategist scrive quella che conta."],
    a: ["Insight agent", "Agente insight"],
    ad: "Customer Journey Analytics",
    op: "Research repository + LLM",
    tr: ["Segment evidence is ready.", "Le evidenze sui segmenti sono pronte."],
    do: ["Clusters research, reviews and behaviour into tension candidates.", "Raggruppa ricerche, recensioni e comportamenti in tensioni candidate."],
    out: ["Three drafted tensions with sources.", "Tre tensioni proposte con fonti."],
    gate: ["The strategist writes the final sentence.", "Lo strategist scrive la frase finale."],
    it: { r: "Un elenco di benefici travestito da insight.", lad: ["Lo strategist inventa la frase in un workshop.", "L'agente propone tre tensioni dalle evidenze. Una persona ne sceglie una.", "Le bozze arrivano. Una persona firma comunque la frase."], h: "Lo strategist. Quella frase è il lavoro.", n: "Non scrive una tensione se le evidenze sui segmenti sono vuote." }
  },
  "intel::job::persona-depth": {
    l: ["A persona the creative team can use.", "Una persona che il team creativo può usare davvero."],
    b: ["The agent proposes two persona cards grounded in the segment. The strategist shapes them into a creative tool.", "L'agente propone due schede persona basate sul segmento. Lo strategist le trasforma in uno strumento creativo."],
    a: ["Persona agent", "Agente persona"],
    ad: "Real-Time CDP profiles",
    op: "CRM + research repository",
    tr: ["Tension is signed.", "La tensione è firmata."],
    do: ["Drafts motivations, context and barriers from evidence.", "Propone motivazioni, contesto e barriere dalle evidenze."],
    out: ["Persona cards on the brief.", "Schede persona sul brief."],
    gate: ["Strategist owns the card.", "Lo strategist è responsabile della scheda."],
    it: { r: "Un catalogo di 20 persona che nessuno apre.", lad: ["A un designer si dice “il nostro target”.", "L'agente propone due schede. Lo strategist le modifica.", "Le schede si allegano. I nuovi pubblici restano umani."], h: "Lo strategist è responsabile della scheda.", n: "La profondità è uno strumento creativo. Le evidenze restano in Segment evidence." }
  },
  "intel::job::category-signals": {
    l: ["What is moving in the category right now.", "Cosa si muove nella categoria in questo momento."],
    b: ["The agent ranks news, search and social signals against the mandate and dates every entry.", "L'agente ordina segnali da news, ricerca e social rispetto al mandato e data ogni voce."],
    a: ["Signals agent", "Agente segnali"],
    ad: "Adobe LLM Optimizer · AEP Data Insights Agent",
    op: "Social listening + news and search feeds",
    tr: ["Continuous; refreshed when a mandate opens.", "Continuo; si aggiorna all'apertura di un mandato."],
    do: ["Scans sources, scores relevance, removes duplicates.", "Analizza le fonti, valuta la rilevanza, elimina i duplicati."],
    out: ["Dated signal log.", "Registro dei segnali datato."],
    gate: ["Strategist removes noise.", "Lo strategist elimina il rumore."],
    it: { r: "Una rassegna settimanale che nessuno legge.", lad: ["Uno stagista incolla link.", "L'agente ordina i segnali rispetto al mandato. Una persona taglia.", "I segnali rilevanti si allegano da soli."], h: "Lo strategist elimina il rumore.", n: "Ogni segnale ha una data prima di entrare in un brief." }
  },
  "intel::job::competitive-scan": {
    l: ["What competitors are saying and spending.", "Cosa dicono e quanto investono i competitor."],
    b: ["The agent compiles competitor messages, offers and presence. The strategist names the gap.", "L'agente raccoglie messaggi, offerte e presenza dei competitor. Lo strategist individua lo spazio libero."],
    a: ["Competitive agent", "Agente competitivo"],
    ad: "Adobe LLM Optimizer (AI visibility)",
    op: "Competitive intelligence + social listening",
    tr: ["Market scope is set.", "Il perimetro di mercato è definito."],
    do: ["Collects ads, claims, prices and AI-search visibility of competitors.", "Raccoglie annunci, claim, prezzi e visibilità nella ricerca AI dei competitor."],
    out: ["Competitive note with sources.", "Nota competitiva con fonti."],
    gate: ["Strategist owns the gap.", "Lo strategist è responsabile della lettura."],
    it: { r: "Uno screenshot in un thread di chat.", lad: ["Qualcuno ha visto un annuncio andando al lavoro.", "L'agente compila l'analisi. Lo strategist segna lo spazio libero.", "L'analisi si aggiorna. Lo spazio libero richiede ancora una frase umana."], h: "Lo strategist è responsabile della lettura.", n: "Non nomina mai un competitor nei testi in uscita, salvo che i Do-nots lo consentano." }
  },
  "intel::job::market-matrix": {
    l: ["Which markets are in, and how.", "Quali mercati sono inclusi, e come."],
    b: ["The agent proposes the rollout matrix from the mandate and past rollouts. Regional leads confirm in or out.", "L'agente propone la matrice di rollout da mandato e rollout passati. I responsabili regionali confermano chi entra e chi no."],
    a: ["Rollout agent", "Agente rollout"],
    ad: "Workfront",
    op: "Location master + work management",
    tr: ["Mandate lists target regions.", "Il mandato indica le regioni target."],
    do: ["Builds markets × languages × channels with local constraints.", "Costruisce mercati × lingue × canali con i vincoli locali."],
    out: ["Rollout matrix.", "Matrice di rollout."],
    gate: ["Regional marketing confirms local scope.", "Il marketing regionale conferma il perimetro locale."],
    it: { r: "“Tutti i mercati” scritto su un brief.", lad: ["Le regioni si aggiungono alla seconda review.", "L'agente propone la matrice da mandato e Brain. I responsabili regionali confermano.", "I rollout standard si compilano da soli. Le eccezioni restano umane."], h: "Il marketing regionale conferma cosa entra e cosa no a livello locale.", n: "Una matrice mancante è il motivo per cui la produzione si inventa lavoro." }
  },
  "intel::job::product-truth": {
    l: ["The facts about the product, from the source.", "I fatti sul prodotto, dalla fonte."],
    b: ["The agent pulls current specs, prices and availability from the catalogue. Product confirms anything new.", "L'agente recupera specifiche, prezzi e disponibilità aggiornati dal catalogo. Il product conferma ogni novità."],
    a: ["Product truth agent", "Agente product truth"],
    ad: "AEM Assets / Commerce catalogue",
    op: "Product catalogue / PIM",
    tr: ["Offer scope is named.", "Il perimetro dell'offerta è definito."],
    do: ["Retrieves facts and flags gaps or conflicting sources.", "Recupera i fatti e segnala lacune o fonti in conflitto."],
    out: ["Truth sheet with sources.", "Scheda prodotto con fonti."],
    gate: ["Product owner confirms facts not yet in the Brain.", "Il product owner conferma i fatti non ancora nel Brain."],
    it: { r: "Un one-pager commerciale dell'anno scorso.", lad: ["Qualcuno chiede al product in chat.", "L'agente recupera i fatti aggiornati. Il product conferma.", "I prodotti noti si compilano. Quelli nuovi restano umani."], h: "Il product owner conferma i fatti non ancora presenti nel Company Brain.", n: "Se il catalogo è vuoto, si ferma. Non tira a indovinare." }
  },
  "intel::job::substantiation": {
    l: ["Every claim paired with its proof.", "Ogni claim abbinato alla sua prova."],
    b: ["The agent maps each claim to its evidence. Unpaired claims stop until legal clears them.", "L'agente collega ogni claim alla sua evidenza. I claim senza prova si fermano finché il legale non li approva."],
    a: ["Substantiation agent", "Agente di sostanziazione"],
    ad: "Adobe Brand Intelligence · AEM Assets",
    op: "Claims register + document store",
    tr: ["Allowed claims and truth sheet exist.", "Esistono claim ammessi e scheda prodotto."],
    do: ["Links sources, checks validity dates, lists gaps.", "Collega le fonti, verifica le scadenze, elenca le lacune."],
    out: ["Source map.", "Mappa delle fonti."],
    gate: ["Legal signs unpaired claims.", "Il legale firma i claim senza prova."],
    it: { r: "Il legale che lo scopre all'ultima review.", lad: ["Il legale è una sorpresa alla fine.", "L'agente mappa le fonti. Il legale chiude le lacune.", "Le coppie approvate si allegano. I claim nuovi fermano il processo."], h: "Il legale firma i claim senza prova.", n: "Lavora con la Claim library. Non inventa evidenze." }
  },
  "intel::job::offer-lock": {
    l: ["One offer, committed.", "Un'unica offerta, confermata."],
    b: ["The agent lists eligible offers with margin and stock context. The demand owner and brand lock one.", "L'agente elenca le offerte ammissibili con margini e disponibilità. Demand owner e brand ne confermano una."],
    a: ["Offer agent", "Agente offerta"],
    ad: "Workfront approvals",
    op: "Work management + pricing data",
    tr: ["Truth sheet and source map are ready.", "Scheda prodotto e mappa fonti sono pronte."],
    do: ["Compares eligible offers and their constraints.", "Confronta le offerte ammissibili e i loro vincoli."],
    out: ["Offer options for decision.", "Opzioni di offerta per la decisione."],
    gate: ["Demand owner plus brand lock the offer.", "Demand owner e brand bloccano l'offerta."],
    it: { r: "Tre offerte, nessuna confermata.", lad: ["L'offerta cambia a ogni review.", "L'agente elenca le offerte ammissibili. Una persona ne blocca una.", "Le offerte standard si precompilano. Il blocco resta umano."], h: "Demand owner e brand. Bloccare l'offerta è il lavoro.", n: "Il brief non viene compilato senza questo blocco." }
  },
  "intel::job::channel-hypothesis": {
    l: ["Where the work should run, and why.", "Dove deve girare la campagna, e perché."],
    b: ["The agent ranks channels using the last cycle's response curves and audience reach.", "L'agente ordina i canali usando le curve di risposta del ciclo precedente e la copertura del pubblico."],
    a: ["Channel agent", "Agente canali"],
    ad: "AEP Data Insights Agent · Mix Modeler",
    op: "Media analytics + BI",
    tr: ["Audience and objective are set.", "Pubblico e obiettivo sono definiti."],
    do: ["Ranks channels by expected contribution and cost.", "Ordina i canali per contributo atteso e costo."],
    out: ["Channel hypothesis.", "Ipotesi di canale."],
    gate: ["Media / digital lead confirms.", "Il media o digital lead conferma."],
    it: { r: "Ripartire dal mix dell'anno scorso.", lad: ["Il mix è un'abitudine.", "L'agente ordina i percorsi. Il media lead conferma.", "L'ipotesi si precompila dall'ultimo mandato simile."], h: "Media o digital lead.", n: "Non compra media. Non apre account pubblicitari." }
  },
  "intel::job::journey-moments": {
    l: ["The moments that matter in the journey.", "I momenti che contano nel percorso del cliente."],
    b: ["The agent drafts the moments map from journey data. The experience lead decides which moments the campaign must win.", "L'agente propone la mappa dei momenti dai dati di journey. L'experience lead decide quali momenti la campagna deve vincere."],
    a: ["Journey agent", "Agente journey"],
    ad: "AJO Journey Agent · Customer Journey Analytics",
    op: "Journey analytics + CRM",
    tr: ["Channel hypothesis exists.", "Esiste un'ipotesi di canale."],
    do: ["Maps triggers, touchpoints and drop-offs to campaign roles.", "Collega trigger, touchpoint e abbandoni ai ruoli della campagna."],
    out: ["Moment map.", "Mappa dei momenti."],
    gate: ["Experience or CRM lead edits.", "L'experience o CRM lead modifica."],
    it: { r: "Un'unica hero che deve fare tutti i lavori.", lad: ["Tutto è un film hero.", "L'agente propone i momenti. L'experience lead modifica.", "I percorsi standard si precompilano. Quelli nuovi restano umani."], h: "Experience o CRM lead.", n: "È il passaggio che la produzione trasforma in asset per ogni momento." },
    n: "This is the handoff Production turns into assets for each moment."
  },
  "intel::job::constraints-pack": {
    l: ["Dates, money and mandatory specs in one place.", "Date, budget e specifiche obbligatorie in un unico posto."],
    b: ["The agent compiles deadlines, budget, formats and local rules so production does not discover them late.", "L'agente raccoglie scadenze, budget, formati e regole locali, così la produzione non li scopre all'ultimo."],
    a: ["Constraints agent", "Agente vincoli"],
    ad: "Workfront",
    op: "Work management + resource calendar",
    tr: ["Matrix and plan are drafted.", "Matrice e piano sono in bozza."],
    do: ["Collects constraints from mandate, calendar and market matrix.", "Raccoglie i vincoli da mandato, calendario e matrice di mercato."],
    out: ["Constraints pack.", "Pack dei vincoli."],
    gate: ["MarOps confirms dates and money.", "MarOps conferma date e budget."],
    it: { r: "Scoprire che il go-live è martedì.", lad: ["I vincoli escono a voce al kickoff.", "L'agente li compila da mandato e calendario. Una persona conferma.", "I vincoli standard si allegano. Le date richiedono sempre una persona."], h: "MarOps conferma date e budget.", n: "Se il pack è vuoto, il compilatore del brief si ferma." }
  },
  "intel::job::creative-brief": {
    l: ["One page the agency can work from.", "Una pagina da cui l'agenzia può lavorare."],
    b: ["The compiler assembles mandate, audience, codes, proof and plan into one brief. The strategist edits and signs.", "Il compilatore unisce mandato, pubblico, codici, prove e piano in un unico brief. Lo strategist modifica e firma."],
    a: ["Brief compiler", "Compilatore del brief"],
    ad: "Microsoft Copilot · Workfront",
    op: "Agent orchestration + document store",
    tr: ["All strategy inputs are complete.", "Tutti gli input strategici sono completi."],
    do: ["Assembles, checks completeness, flags contradictions.", "Assembla, verifica la completezza, segnala le contraddizioni."],
    out: ["Draft creative brief.", "Bozza di creative brief."],
    gate: ["Strategist and demand owner sign.", "Strategist e demand owner firmano."],
    it: { r: "Un workshop di kickoff che in realtà è strategia, fatturato come produzione.", lad: ["Lo strategist scrive il brief da zero.", "Il compilatore assembla. Lo strategist modifica e firma.", "L'assemblaggio è automatico. La firma no."], h: "Strategist e demand owner.", n: "È l'oggetto di passaggio. La produzione legge solo questo, più il Brain." }
  },
  "intel::job::comms-legal-pack": {
    l: ["Everything comms and legal need, before the work.", "Tutto ciò che serve a comunicazione e legale, prima del lavoro."],
    b: ["The agent bundles red lines, claims and proof so comms and legal comment once, in one place.", "L'agente raccoglie linee rosse, claim e prove, così comunicazione e legale commentano una volta sola, in un unico posto."],
    a: ["Compliance pack agent", "Agente pack compliance"],
    ad: "Workfront proofing · Adobe Brand Intelligence",
    op: "Approval workflow + document store",
    tr: ["Draft brief exists.", "Esiste la bozza di brief."],
    do: ["Builds the review pack and routes it to the right reviewers.", "Prepara il pack di revisione e lo instrada ai revisori giusti."],
    out: ["Comms / legal pack.", "Pack comunicazione / legale."],
    gate: ["Corporate comms and legal comment and clear.", "Comunicazione corporate e legale commentano e approvano."],
    it: { r: "Inoltrare l'intero brief al legale con “fyi”.", lad: ["Il legale è in copia su tutto.", "L'agente prepara il pack. Comunicazione e legale commentano in un unico posto.", "Il pack si allega. Le eccezioni richiedono sempre una persona."], h: "Comunicazione corporate e legale.", n: "Le approvazioni useranno questo pack come gate." }
  },
  "intel::job::next-cycle-intake": {
    l: ["Decide now what we want to learn.", "Decidere adesso cosa vogliamo imparare."],
    b: ["Before launch the agent creates the learning slots: the questions this campaign must answer, tied to agreed KPIs.", "Prima del lancio l'agente crea gli slot di apprendimento: le domande a cui la campagna deve rispondere, legate a KPI concordati."],
    a: ["Learning-slot agent", "Agente slot di apprendimento"],
    ad: "Customer Journey Analytics",
    op: "BI + KPI dictionary",
    tr: ["Brief is signed.", "Il brief è firmato."],
    do: ["Proposes hypotheses and KPIs from the dictionary.", "Propone ipotesi e KPI dal dizionario."],
    out: ["Learn slots on the record.", "Slot di apprendimento sul record."],
    gate: ["Analytics lead owns the answers after flight.", "L'analytics lead risponde agli slot dopo la campagna."],
    it: { r: "Un report che finisce in un cassetto.", lad: ["Gli apprendimenti sono una slide al wash-up.", "Gli slot si definiscono prima. Le persone scrivono le risposte dopo.", "Gli slot si precompilano dal dizionario KPI. Le risposte arrivano da Learn."], h: "L'analytics lead risponde agli slot dopo la campagna.", n: "Per questo il modello migliora a ogni ciclo. Senza slot, nulla torna nel Brain." },
    n: "This is why the model compounds every cycle. Without slots, nothing writes back."
  }
});
